[package]
name = "nbtq-cli"
version = "0.0.0"
edition = "2024"
homepage = "https://github.com/Vonr/nbtq"
repository = "https://github.com/Vonr/nbtq"

[[bin]]
name = "nbtq"

[dependencies]
nbtq-core = { path = "../nbtq-core", features = ["colours"] }
jaq-core = "3"
jaq-std = "3"
flate2 = "1.1.9"
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/{ version }/{ name }-{ version }-{ target }{ archive-suffix }"
bin-dir = "{ name }-{ version }-{ target }/{ bin }{ binary-ext }"
pkg-fmt = "tgz"
disabled-strategies = ["quick-install", "compile"]

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-fmt = "zip"

[package.metadata.binstall.overrides.x86_64-pc-windows-gnu]
pkg-fmt = "zip"
